### ISSUE TITLE
Alternatives: More Emacs-style hacks

### ISSUE THREAD

**Issue by TriMoon** [kvs/STEmacsModelines#11]
This link's destination is a 404 !

**Comment by frou** [comment]
The content got preserved in the internet archive: https://web.archive.org/web/20120226212821/http://software.clapper.org/ST2EmacsMiscellanea/

**Comment by TriMoon** [comment]
3 years later finally noticed :rofl: 
I totally forgot about this as i have moved to atom...
But nice, time to change that link in the readme then :wink:
